// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Option = require("rescript/lib/js/belt_Option.js");

var env = process.env;

var gqlSchema = Belt_Option.getWithDefault(env.GQL_SCHEMA, "../schema.graphql");

var graphConfig = Belt_Option.getWithDefault(env.GRAPH_CONFIG, "./subgraph.yaml");

var codegenConfigPath = Belt_Option.getWithDefault(env.CODEGEN_CONFIG_PATH, "./config.yaml");

var genaretdFolderName = Belt_Option.getWithDefault(env.GENERATED_FOLDER_NAME, "generated");

var outputTestFilePath = "./tests/" + genaretdFolderName + "/";

var outputEntityFilePath = "./src/" + genaretdFolderName + "/";

exports.env = env;
exports.gqlSchema = gqlSchema;
exports.graphConfig = graphConfig;
exports.codegenConfigPath = codegenConfigPath;
exports.genaretdFolderName = genaretdFolderName;
exports.outputTestFilePath = outputTestFilePath;
exports.outputEntityFilePath = outputEntityFilePath;
/* env Not a pure module */
