networkConfig:
  entityIdPrefixes:
    - networks:
        - mainnet
      prefix: ""
    - networks:
        - ganache
      prefix: local
entitySettings:
  Gravatar:
    useDefault: {}
    setters:
      - name: updateGravatar
        fields:
          - owner
          - displayName
          - imageUrl
      - name: setOwner
        fields:
          - owner
      - name: setDisplayName
        fields:
          - displayName
      - name: setImageUrl
        fields:
          - imageUrl
    entityId:
      - name: gravityId
        type: BigInt
  Transaction:
    useDefault: {}
    entityId:
      - name: transactionId
        type: Bytes
