networkConfig:
  entityIdPrefixes:
    - networks:
        - mainnet
      prefix: ""
    - networks:
        - ganache
      prefix: local
entitySettings:
  Gravatar:
    useDefault: {}
    setters:
      - name: updateGravatar
        fields:
          - owner
          - displayName
          - imageUrl
      - name: setOwner
        fields:
          - owner
      - name: setDisplayName
        fields:
          - displayName
      - name: setImageUrl
        fields:
          - imageUrl
    entityId:
      - name: gravityId
        type: BigInt
  Transaction:
    useDefault: {}
    entityId:
      - name: transactionId
        type: Bytes
  TokenLockWallet:
    useDefault:
      manager: {}
      initHash: {}
      beneficiary: {}
      tokenDestinationsApproved: {}
      managedAmount: {}
      startTime: {}
      endTime: {}
      periods: {}
      releaseStartTime: {}
      vestingCliffTime: {}
      tokensReleased: {}
      tokensWithdrawn: {}
      tokensRevoked: {}
      blockNumberCreated: {}
      revocable: {}
      txHash: {}
    entityId:
      - name: id
        type: Address
    setters:
      - name: setTokensReleased
        fields:
          - tokensReleased
      - name: setTokensWithdrawn
        fields:
          - tokensWithdrawn
      - name: setTokensRevoked
        fields:
          - tokensRevoked
      - name: setTokenDestinationsApproved
        fields:
          - tokenDestinationsApproved
      - name: updateManager
        fields:
          - manager
  GraphAccount:
    useDefault:
      names: {}
      defaultName: {}
      defaultDisplayName: {}
      isOrganization: {}
      metadataHash: {}
      codeRepository: {}
      description: {}
      image: {}
      website: {}
      displayName: {}
      operatorOf: {}
      subgraphs: {}
      developerCreatedAt: {}
      createdDisputes: {}
      disputesAgainst: {}
      curator: {}
      indexer: {}
      delegator: {}
      nameSignalTransactions: {}
    entityId:
      - name: id
        type: String
    setters:
      - name: setOperators
        fields:
          - operators
  NameSignalTransaction:
    useDefault: {}
    entityId:
      - name: id
        type: String
    setters:
      - name: setSigner
        fields:
          - signer
