name: Deploy docs to ghpages - CD
on:
  push:
    branches:
      - dp/docs-cd # TODO
jobs:
  publish:
    name: Deploy Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: cd docs && yarn
      - run: cd docs && yarn deploy
