name: Compile Rescript & Test template graphs - CI
on: pull_request
jobs:
  publish:
    name: Compile & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install uncrashable package dependencies
        run: cd package && yarn
      - name: Build dependencies
        run: cd package && yarn res:build
      - name: Cache dependencies
        id: cache_graph
        uses: actions/cache@v2
        with:
          path: ./templates/gravatar-test/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('./templates/gravatar-test/yarn.lock') }}
      - name: install gravatar graph dependencies
        if: steps.cache_graph.outputs.cache-hit != 'true'
        id: install_node_packages_graph
        run: cd templates/gravatar-test && yarn
      - name: Run graph-cli codegen
        run: cd templates/gravatar-test && yarn codegen
      - name: Run uncrashable graph development package
        run: cd templates/gravatar-test && yarn uncrashable-dev
      - name: Run gravatar tests
        run: cd templates/gravatar-test && yarn test
      - name: install token lock graph dependencies
        if: steps.cache_graph.outputs.cache-hit != 'true'
        id: install_node_packages_graph_demo_subgraph
        run: cd templates/demo-subgraph && yarn
      - name: Run graph-cli codegen
        run: cd templates/demo-subgraph && yarn codegen
      - name: Run uncrashable graph development package
        run: cd templates/demo-subgraph && yarn uncrashable-dev
      - name: Run timelock tests
        run: cd templates/demo-subgraph && yarn test
